# Ultralytics YOLO 🚀, AGPL-3.0 license
"""
Ultralytics modules.

Example:
    Visualize a module with Netron.
    ```python
    from ultralytics.nn.modules import *
    import torch
    import os

    x = torch.ones(1, 128, 40, 40)
    m = Conv(128, 128)
    f = f'{m._get_name()}.onnx'
    torch.onnx.export(m, x, f)
    os.system(f'onnxslim {f} {f} && open {f}')  # pip install onnxslim
    ```
"""

from .block import (
    C1,
    C2,
    C3,
    C3k,
    C3k2,
    C3TR,
    C2PSA,
    DFL,
    SPP,
    SPPELAN,
    SPPF,
    ADown,
    BNContrastiveHead,
    Bottleneck,
    BottleneckCSP,
    C2f,
    C2fAttn,
    C3Ghost,
    C3x,
    CBFuse,
    CBLinear,
    ContrastiveHead,
    GhostBottleneck,
    HGBlock,
    HGStem,
    ImagePoolingAttn,
    Proto,
    RepC3,
    RepNCSPELAN4,
    ResNetLayer,
    Silence,
)
from .conv import (
    CBAM,
    ChannelAttention,
    Concat,
    Conv,
    Conv2,
    ConvTranspose,
    DWConv,
    DWConvTranspose2d,
    Focus,
    GhostConv,
    LightConv,
    RepConv,
    SpatialAttention,
)
from .head import OBB, Classify, Detect, Pose, RTDETRDecoder, Segment, WorldDetect, v11Detect, v11Segment
from .transformer import (
    AIFI,
    MLP,
    DeformableTransformerDecoder,
    DeformableTransformerDecoderLayer,
    LayerNorm2d,
    MLPBlock,
    MSDeformAttn,
    TransformerBlock,
    TransformerEncoderLayer,
    TransformerLayer,
)

from .mamba_yolo import (
    CrackVSSBlock,
    CrackVSSBlockV2,
    CrackMemoryVSSBlock,
    CrackStructureVSSBlock,
    UnifiedCrackAwareVSSBlock,
    LastUnifiedCrackAwareVSSStage,
    EfficientCrackAlignedState,
    AdaptiveC3k2CASP,
    SparseCrackPathState,
    AdaptiveC3k2CrackPath,
    AdaptiveC2fCrackPath,
    AdaptiveC3CrackPath,
    AdaptiveC2fCASP,
    CrackDetailStemLite,
    CrackDetailStemDirectional,
    CrackMergeLite,
    CrackMergeDirectional,
    CrackWriteVSSBlock,
    CenteredCrackWriteVSSBlock,
    LastCrackWriteVSSStage,
    LastCenteredCrackWriteVSSStage,
    DiagonalOrientationVSSBlock,
    OrientationVSSBlock,
    CrackXSSBlock,
    CrackXSSBlockV2,
    SimpleStem,
    VisionClueMerge,
    VSSBlock,
    XSSBlock,
)

__all__ = (
    "Conv",
    "Conv2",
    "LightConv",
    "RepConv",
    "DWConv",
    "DWConvTranspose2d",
    "ConvTranspose",
    "Focus",
    "GhostConv",
    "ChannelAttention",
    "SpatialAttention",
    "CBAM",
    "Concat",
    "TransformerLayer",
    "TransformerBlock",
    "MLPBlock",
    "LayerNorm2d",
    "DFL",
    "HGBlock",
    "HGStem",
    "SPP",
    "SPPF",
    "C1",
    "C2",
    "C3",
    "C3k",
    "C3k2",
    "C2f",
    "C2fAttn",
    "C3x",
    "C3TR",
    "C3Ghost",
    "GhostBottleneck",
    "Bottleneck",
    "BottleneckCSP",
    "Proto",
    "Detect",
    "Segment",
    "Pose",
    "Classify",
    "TransformerEncoderLayer",
    "RepC3",
    "RTDETRDecoder",
    "AIFI",
    "DeformableTransformerDecoder",
    "DeformableTransformerDecoderLayer",
    "MSDeformAttn",
    "MLP",
    "ResNetLayer",
    "OBB",
    "WorldDetect",
    "ImagePoolingAttn",
    "ContrastiveHead",
    "BNContrastiveHead",
    "RepNCSPELAN4",
    "ADown",
    "SPPELAN",
    "CBFuse",
    "CBLinear",
    "Silence",
    "C2PSA",
    "v11Detect",
    "v11Segment",
    "SimpleStem", "VisionClueMerge", "VSSBlock", "XSSBlock", "CrackVSSBlock", "CrackXSSBlock",
    "CrackVSSBlockV2", "CrackXSSBlockV2",
    "OrientationVSSBlock", "DiagonalOrientationVSSBlock", "CrackWriteVSSBlock",
    "CenteredCrackWriteVSSBlock", "LastCrackWriteVSSStage", "LastCenteredCrackWriteVSSStage",
    "CrackMemoryVSSBlock", "CrackStructureVSSBlock",
    "UnifiedCrackAwareVSSBlock", "CrackDetailStemLite", "CrackDetailStemDirectional",
    "LastUnifiedCrackAwareVSSStage", "EfficientCrackAlignedState",
    "AdaptiveC3k2CASP", "AdaptiveC2fCASP",
    "SparseCrackPathState", "AdaptiveC3k2CrackPath", "AdaptiveC2fCrackPath", "AdaptiveC3CrackPath",
    "CrackMergeLite", "CrackMergeDirectional"
)
